version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build

jobs:
  build:
    working_directory: ~/ExampleApplication
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: test-run
          command: npm run test
      - run:
          name: docker-login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: build-docker-image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: publish-docker-image
          command: docker push $IMAGE_NAME
      - run:
          name: set-environment-variables
          command: echo $SERVER > server.crt && echo $PRIVATE_KEY > privatekey.pem
      - run:
          name: build-docker-image-for-integration-environment
          command: docker create -p 2814:2814 --name $CONTAINER_NAME $IMAGE_NAME
      - run:
          name: copy-server-cert-and-private-key-across
          command: docker cp ./privatekey.pem $CONTAINER_NAME:/privatekey.pem;docker cp ./server.crt $CONTAINER_NAME:/server.crt
      - run:
          name: start-docker-container
          command: docker start $CONTAINER_NAME
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export SERVER=\"$SERVER\"; export IMAGE_NAME=\"$IMAGE_NAME\"; export PRIVATE_KEY=\"$PRIVATE_KEY\"; rm -rf ExampleApplication/; git clone https://github.com/rduffyncirl/ExampleApplication.git; source ExampleApplication/deploy.sh"